"""init

Revision ID: 515564c6b6ca
Revises: 
Create Date: 2026-07-25 17:52:24.197981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '515564c6b6ca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allergens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description_en', sa.String(length=200), nullable=False),
    sa.Column('description_nl', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('units_per_box', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meat_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description_en', sa.String(length=200), nullable=False),
    sa.Column('description_nl', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('item_allergen',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('allergen_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['allergen_id'], ['allergens.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('item_id', 'allergen_id')
    )
    op.create_table('item_meat_type',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('meat_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['meat_type_id'], ['meat_types.id'], ),
    sa.PrimaryKeyConstraint('item_id', 'meat_type_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_meat_type')
    op.drop_table('item_allergen')
    op.drop_table('meat_types')
    op.drop_table('items')
    op.drop_table('allergens')
    # ### end Alembic commands ###
